# Generated by Django 4.1.7 on 2023-04-09 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watermarker', '0003_alter_watermark_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('watermark_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='watermarker.watermark')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watermarks', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('watermarker.watermark',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
