# Generated by Django 4.1.7 on 2023-03-22 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watermarker', '0003_alter_watermark_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('watermark_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='watermarker.watermark')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('watermarker.watermark',),
        ),
    ]
